### PR TITLE
Re-implement `fetch!` with DBCollection API v3.4

### PR DESCRIPTION
**Pull request by marksto**
See #173 for the background story of this change.

### CODE REVIEW

**Comment by marksto** [comment]
@jheander here's the tough one. I was as careful as physically possible with migrating this combo `fetch` function.

Here is the list of possible backward compatibility issues that prevented it from being perfect:
1. The `read-preference` param is added alongside with pre-existing `read-preferences` (which should be dropped);
2. The `options` param is still present, but it uses a custom data format and is now covered with a complete set of newly added options (so should be dropped as well);
3. The `set-options!` (which is a public implementation detail, no less, no more) was renamed to `set-cursor-options!` (and should be dropped together with the `options` param).

I propose to address (remove) all of them during the next major 'congomongo' release.

**Comment by marksto** [comment]
BTW, the https://github.com/mongodb/mongo-java-driver/pull/803 is shipped now, so we should be able to upgrade to the 4.4 version of the Java driver these days.

**Comment by jheander** [comment]
Thanks for the list of backwards compatibility issues! But doesn't the rename of number 3 technically force us to hold this PR for the next major release already?

**Comment by jheander** [comment]
Good news with the fix to the java driver!

**Comment by marksto** [comment]
About the rename thing. This one is a non-reusable `fetch` fn-specific implementation detail, internal to the lib, and it shouldn't have been made public (in a perfect world). So, for me personally this is ok to make it private, because I can hardly imagine anyone actually using it. And nevertheless, to make us feel more confident, I temporarily brought it back in a form of alias.

**Comment by jheander** [comment]
Oh, I see. Well, with the alias there we can do a minor release and then add it to the list of things to clean up for the next major.

**Pull request merged**
